# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef0f381da5c9db09a9030ecda51dff5cc1b5a1ba59065ef1e19ebfa11fafe714abf2e0d5fd02909a20f2a69741faccb78bbbc3afb5d04468493eb78c7379c2b3

test:
  secret_key_base: 8543ed7baf096f58a6c45414f0660542f9ae72d58b0c30077013eecb4dfe9c18ca86f8ef66a774684e0b5c65b790e6f631634cee4f0d77db701fbf4d853557f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
