#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA0lGwjh/TTbLh+up4zXzwUeSf/e1C5pWir2fuP8AwJbuO8XEQ
    mAwXGgBhtik+AnwSkUgr7uiHQVM1AAyOluomTJ5/WMUe/K+hUwLzjrL4NVMy+1Rh
    jlcdybyiuGYg+cWLbiKbCNdJrlReZWlTwr+fKQAahP+Lxb18x5CkaNQg2OefgG4W
    I5aKtDkA3q7FGaNOZkqBpa9jFdjQ/PvK5/rP/nk1m/hgx3z6hCU/9Pwz9LT5DRLo
    J+lPVRgZtu0rIglfPaholjVi4Gio3fmK0tO44IcfiquVsT9p0ae5u0qgPS2r8uW9
    B4vmZWGMvmkK85fUA+bJceSOlAvP6Nwe4qRo7wIDAQABAoIBAQCkpxVsvtejLZci
    4+t9HAHcavsiRVwpvx3k6p2nxSMsdyCaPqT6FAUF8ySMAs+sDExQ9sqGN/6jkquc
    hTggR+GB/FfAPFpdAnZu0ZGxtsUAokj4YAAb+nG0nPxbFoFcaV4V8/uhuUHSu/RG
    umW7wl6tL4qTcqiPPyBv7/n2o5OvmoJ+BHIz57RDQZB8Jq6U1tjn9IxvscF5mk1E
    TrodpDgqA55aqQcdf6qCTjEGi1E+rhirxXxlKCMV+C3dqU0q+5DtPmxIdJUCZQsK
    76fFtjBl+nDkMWdDpAeOtX7GbmvoefhFJ5S0z6bhSbk2YgLmqBKOS+4GUlevPD//
    yB0e0I4JAoGBAOmpGNNzgDxBWt3q9N0jaTmqadF1nWP822rNkYda3DgwT8CTqNF1
    c1F29k3BYFuLhGyaz1AW0BShhybEvOM6T0aHHsHr+fV6oNkt8/4+EUBz4SySpWEM
    xJyeGijpZ2DnBSQ2Ye/x+iF1iMpD0rovbSzAgDtfpjALRHRxZtjJ7qibAoGBAOZt
    ThB++GIVNtzGb1z8EpCZ3IuA01i38Zq+CX0vGCW+Fiz06haJBh9qDkhfcgimbMp8
    wuWqmZ/wd7UkGTR4KVMU/ll6FVwMiCHWBM6hl9BifsleHANFPL2Crq8fNcnIYVZ3
    /mkbMiQDdSzgP6Pk6xXM6SpX6otfaRfWepz3IHQ9AoGBAMws4a+rxstgRHmUXQF7
    dvBX0/2e67g6dLUACoGfSL2koZviq2rUWb8+130cVAnKgR2xrSQLuym79/BNi8x2
    4Fz9p0fG3vW9gR4lxIZOUB7k40dioTaLxKYilTNYuOf5FwoMp0nXRT3FiZFM8K+W
    z6yCTcsUCpEC1390tG0NDwmvAoGAF2YcGkK6eENNOegQoPGb9QEayzO+wnCTYTJR
    BlxE6HhACjqolrc9Xu1HHARNMSGtRHac1/OV/A7QKR3MTW6yS5SDK5ThHGLNZBo2
    jMEOCIQn+czLrW1XeKsPkArsTFxDviMbO5MeaVfMi00OSVdSo/kV6E3bLGH46wnF
    k7Doo8UCgYASgyj7upnhXJasw3+2dY1IQ3YlMTh/Oz2JQITjRIqiTHTkiGOInI9V
    7W+nzXPQZ9Z2fyrySHbOyP5lxDe3NY3PLKNb5BMR613XhfrBcCglXAEzFI3WOffk
    lLLFZeYrfxs6zt7dmaaXnNuLZVX9pet2tqmAwROg1aCwSBa2Rj7B1Q==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['RELEASE_KEY1'] %>"
      iv:                "a0CC7YbTk25C4lCfolC0aA=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEApjATLwFWrZ0Ymw/1g64WzeksNvXrVH+aODmDkN35eRpa8wwI
    bLRm8dP9d2gxqaAyD2hm3fzrn/frKVakv3V7Wx+bHgmCNv+rhBQuJ/B5wDmC5yMu
    nnyfWBZumm/CRyIsGpGx9FMHigg75myRRYIS2aCP9sgTai9GbaTM77VHHCurxLeM
    QD5+C9S5I93P9rfkKY1yQZ80qCww+Z2TQrPuHjtL/bXSV0XnCIvX2w50ZcKghwuw
    0aYHz82IlXg+/CcFVZeQAppY8Rn1X3Lgimd/TW6my4fjXXNd6/mZjRpPc2RYPYxA
    l22o/LMiC4Xyah80ZvytUmsMDN//CccL1J4WBQIDAQABAoIBAGZ2AX3bn2tPDhqc
    TkyvitPNTTtdh4gDXDwKCbnJgcROoYB0DMWovEeg4gc6sFPatsKVJcb75vIr0ksc
    Zlq8vh9Cb0qnpibunvrBzmtFcms3iiOjp1yDjWKsAekpumhNA1AmP8dZYa6SwQui
    KDboqWKQAfKvDHlNSGjVUJ0B8SPGMjRmcjPOww4abaR5sIMWGLGoCDv8VlnmiB6G
    PI2Z9HtR34o7vpv6FlWyWsaoY0EIi908qzfOACkeIveqwKEh5/tNjYQ2pfCquBPs
    m9rzoj17F4RSA07rdPScEoZrY9HtFvOzlfncYteEvvCOXHTDxiPTk5SoheReDYzX
    SteW/kECgYEA3AD8qoHDplnGLk9BYypUSDffa5OSgPs1TwHclw+8kDd04HH92k7H
    79z6bwc92PFxonZYZK7/nkVq+XUI7Jj/9jKtiB3c9ynzkPa+Jh+x8n2pATiLGdAC
    1VguB3WbWyubeNm8e0ZcPc9p8pcZUAaNSwwuMoLjPJlk8xyi0ULLJqkCgYEAwWD3
    ESvkIuUMu15t47BoJZuI/QLxvCn5hKlkSYIbyKmYauLdQWO7+i/16nl/n/6P/Sd+
    KdS2m0THeTTZqIC2JmfzakaP08ylKirQh9Xf07Ay/pgpDQJQyt+jvMDS/UTNFi0K
    30VrteNTW4r/G/A7yoPdF/Wu8uMnZz5L4Srbef0CgYARoyqeaMTMo0nWEJiHYK9d
    Es2gjDYkjP8bFGUg3ywYy7lc/QaC5+nzet3A5O26ZLDde2tetwDbKWmIEi/i9+kd
    TbbHwM0kK4LRTla0K7pSXGyeInBUY262t9kI1A7eYkKWj64im+NtOSGfRynKVpwh
    NhrGBeQ9yXZkXxlWeWpb8QKBgASdZ8gFICClDrS6AC1a3GFpYM+I7nPrHIVJ9Za7
    gCY9xeFnIJia5LWHx3qdA6qxzIXiF2SwKttxvMDrvfYDfFVWTbzPikcnrxlehDN5
    qynGHrFsuC4TTBJLXAD5KQ/aQHqzAHtrkLJ6hla87nGgPg0LMI+N0WsCeMJB/lWV
    TD+RAoGBAJTEMDyJejGwbPOoDya9KfnVc/Ojw9DJJVerwuYUjCqp0cyjZPTjZq2V
    saCqJQUsU6RV0IYLJVBul0yTxpHo1j+kqhmPgQ55owve7J4FAWtkB51RinQuktVt
    b4HJTgnz//rtuqDZuvUYPno4mp76B1jSa4zNStE/lNhhwUrg9LrT
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:                "j3Y3I34+vU55JqpzShgHUQ=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
