#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0K8SKgx8bCl0im71c75QmKvxc+yrFOcSDTq/UPqCeDmUt9ZE
    ib1EeTjoOfvaL+1kRVcWDSpFg/sDQ1EyG81R1qguZuA43LiJzFYJAjBpLdXQgLNp
    F1IIJd0wFoseEW5A/z9meubsjf+PrZ9E2kpoAoqbtjKNp4yPI9CkMM4TZQanEVSB
    pzb1hipFZgqM9RLEF+WMUU79fDPTRbXjEP1akgL3uBXbjeyt1ES/OwVXejYJckc9
    pegClw+7fPkT9YDSEMLhSecLvhV1r0Jk6U5JyuCo+GNtC+S8u2yKFzkoRDQSsY+L
    BnepV779gb9yIN/nrG99k5+eI8RhAy6gaYEfowIDAQABAoIBAQDP1Ju9fuPngL3N
    JMaU+AQimJOGhTy5O4vR2yEwT9ziSU5gbCekGff41oEJRlc9BiqnmByhDelfkPzl
    7RZ/c9M+eg6EbGiVAcBS3ZhpMrd9a4UUuBlAnXT56Lh8qx5N88UNsCGq4xLSNKPu
    IUGcOSAu78Y2BVDofecMnzz2UjYklFgmqWhGFkbXFKu9z1VzqhL65XcLdWc5jRhD
    gf0nczf97RT+A2letK/aroUD1/h93UODARntI1odIfon7CBZl9Xfhg4uW9PgLHiQ
    O7zwynn6O7JXR1zxvePYxzfS7bYgOJ44h228jgyIsIKpLO78Q3Wv9wZ46Jrx08UO
    SPUVNLE5AoGBAOjoP37Bwa7MJrK9paDTBvL1tfCX8sBsDuYAuNz4Pzuc/syxBN/x
    ZF+9zms573S29Z/9ZI5ehBM6uearb6Q01PR00PMglkuoUTf+6Qqp7xt+r1IdPo0S
    CQB4ODvgLX1FicSW/uVcp89IMibOY9S/lXl5ocsnYpLF/lSmkzB6ALgnAoGBAOVf
    +bR7LeFV6KfC7IRKvr0ZUeqQqljYKjj6WOxIYW7YMQfmVXCgdVfAK/S9XUTgv2uL
    y/enownsjihGrlT2Ak9NKdXDdIEkHdxsMvkLdp/7DQlrZ6FgduqFyK5dLeel/hQI
    2oZzRi9jzqwDJj2NJbn3Zwfodod3xnPmikitZK4lAoGAa6yDPjyhKAhlk5ita65j
    tgr2M+ZraZ4LPTX0QOPbh9nKyiLEWCum9cQwG85K77Bt2asxw8faU3GA5C05jbaH
    BQTEXMIh+ZQ1CCgm4LEzQ4jL0LCIbHt8AeWSScwX+6QcTvBnou20/tUnql0cNgzk
    M6aRr/PjVGuIauYfgffFQV0CgYBhHbW3+L+APMN45EsH6C3CGspYKlA1tbCK11R3
    Fl5KdDauRZO/T/De6nqx8MtgslfZzSLbBJs/RG0cGHEPf+mScfVYkJzvYL9T6Gvc
    jkH3km/+oP8LkLBIs8Q4LzOUdO+Sw/ziGESLJBMJOXwja3OhvWJeMsqcqNXZlK7P
    /ro2EQKBgAJ9UQhNww4Fy0yAucd+emZK/H7QsZBeipq/XoKSYPKXNsRaxV9PomgA
    ln65XKiCFs9MqN6c0tBI3nT0F4P2aVWhF45glpwwPulsWfKEUC3uutgK8xiwuUv1
    Th84ZSCllCnC8p1OePFP4T1AGJbn9aFnpexC13Mwi52XdhU8JT+P
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['RELEASE_KEY1'] %>"
      iv:                "GGU+FCU5Gt5tJcDFT8KT7A=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAlgx8jzRaDulJBVkF6ztyc1gDJgD5w/sV2PwUD4+wdvag2VkN
    cypt+wSd7uuoThyR0f6WWtdP/UY4z0dswtHpV3SG1gPcLn16UOVU723Q150WD+K2
    aNFCdMqippQW7uNF+8ZcOqZ/oFWUYDjLKBaNNOmibRe35njx8WZAFU+nyA8HJELT
    yF6NhvmLg2icSWrtKKmgZpYrYs3xptD3pJ6g7EWnnfLPZJhF0Xy32ozZ0R29AW1t
    2J2aFnG1i31VjACmmNYTOlHu10OsU/fAB8KQc5N0btV6krIky8H7WvsIQEWuruYf
    q3F003Z2zH5jMkcv9JSNTYVUgvhLGqA7D58H6QIDAQABAoIBAClGjg0mrY9khP2/
    m202ESnBkDwoEIzkyQHDdhFByZ0wAtdHM/f2OALRJlDO6qFyInrNubaLfCmD46TB
    VR3SeIniOCUvMqZnRfpy24Zxgv2M7MC58MuspMdT5qJEInrccifsTPqlSn5kjEhb
    1ybT7Uwc6N1xpNj1dDiflAlIvDK/47GCM/CDFybk0vEfa8+dRyt/ym4iO6W1rnL4
    TmKWCGdO+wR7F+BSkTwqZ8nWdWb72EjYli1qEFovkSgThuj5VaG15nbVS4ZV+bzT
    Cdm/2nFim6p6oRa7pBxj3yTfQM+/ekKtM2cRWLhpPHpecSo+/oO9pXv0RqDKJiAb
    JT6K1LECgYEAx+mg8LxEiIO9WTSSQZV2AHhlgV0eKfYTR5MNsHmL002uQT8MzUqF
    XDgC+VaOYthKLaVySczpRDSB/k8BLEZf6w7hQKKiv6IN95IlzUo2XU7jZDNHCHbZ
    mMwcGs0VR2f+Rqh0t2zbJ4yd5pqx99aZnxJzAeiz2UXNYcamsGQ/fhMCgYEAwCV5
    w+HMjGWdL43LqZzSzgFV0Muag9btYo5bJLTAg3nLHLVDGWX7Quhu8+eXGTsJwhKG
    iw2wZCLNwiWkOFEnp1Tav6ri5W3gG0ySomnMqmgm4Azj/lR3NQlccNEsDGda+Vje
    Q6k/dPSSLL4N6sB/JixPbARnHTgLZw1pFCjYMZMCgYAv0VZJvv61mK1l9Qk23sVG
    /4VoGBnq941NBYO0vp4PgPk5ahdp03VqxYsQkP+l7Q5xNK3NsVHqmpSte8BQEtVG
    qFyA1WYQaHbmzPJ11FaEoyYJBarr/2G1Br2CO6PnXJyZ0hl49nTFVQE/86i2G4LL
    ZeJUhpDeW6/wv0+HybLWOQKBgGkRFPAjfDIZLkZehssMUckLud0eODN3Rv7pULVV
    kR9TbdkY1MQCm84OQv1j2Z+WRNO2RZOrvJRE47YR1yZkWgaJw8Oiscc6uZyz1kqx
    B5T2tqs04Uak8TozEDUwa6GssnY+PetJlMVjJrsIgZun/t7kw9kQ30F+79093AOG
    AhG5AoGBAJjoCeerP7daf1tQuOWpEBtq1Tc90EynbPgwn8PCo/lkJSAYGCn/3Zgg
    grVGNRNG+XVKBWvR1W+7m8vtfzCGBf93izUF41TTnynQrugrhpB1LzwxTn4rWZYl
    ZVfr9hTHfMWPhwhVGsebjBAYKaJaDGVzwoPgYBTQOGOACK7ClDyd
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:                "/saaREmR/fdwFU2wDdnmNg=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
