#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAz8tIZsVO8YRSuFkqM0Fs/R9D+YUdMZpW2xgpuPc69NrQk5Do
    1OX2bTC2rUsM6Cgzn56tvh9E/yajLJhADn3Fly78dMNC4ez+IEyHXnpp9Spd0Xtn
    UgetmmodhF49sfQ+icPMLT3ElM9oYmYRHsNqKQFYOfu2zXOrXcdqLXvx/BW3OqGx
    Mnl9RBM7J63Je41WHDC8S1NjRqUymri8QK5wNIuSGJkNiM4grbMn92FhCvKVk5MR
    ZF9uYfYP4S1PQqoNSEsYPDUa27AD8FS552VaPqrYwo0MSfifvj9wvKnouCKA6dUh
    FBOQfUp+BBBOrBKlJY9tshQ6YTuxuI7fQfhMxQIDAQABAoIBAQCArinLAvtNU52K
    biVVEno1Eoyc1BNtKWAKVB9aXThUc8Fg8QdO+I4vtlAaZvS6PFMj0TdVGrY2sC2y
    qyJYFwkrA7zxbg5YLNR/GgVmu7YsTi1FUf987CZVDsvysg3QyymDVQ53Id5ALWU+
    Mmj9vRRcCmohlkDxYGVKMPkO68fCTG69vd+9TI9ZvbQ+El1ZvuWJO8qduGRCMWvO
    xdWUNp8M/Ohfa/NaHE9TM/dZDZhugH1F2qvOOXXmcH4kHc0vsoWCJj7dKyhE2h8V
    ObsprQ6cfNTv8j/fzF3aJUbCAHqPo/FxaSASWlNsDsmMbj2c7wuly8qwID+G9DFg
    nD/k6lfNAoGBAOgxouuy4tqjiX9LvgFrWETOC/82PmwSHPqzY/0PWRxnq/dYOcY9
    GbyvkTwuruYG2PvexIYd2caUcOnRE1Qar+yqYiXsDYzzHMXAjY65UdnjcPmzDoOS
    vt4Ux02ZH7ZMSuUolVjyyTm/au7RtmqAY21u5zIxdTvjFBpl0+OUOX5nAoGBAOUZ
    OjtJyAvLV5GCo+v91msFAMqsHVYOtOCSVh0IZQ6lA9pU3GGrBFHUV4IY9rIesagM
    RTn7W3ZQFonkTQPiCEMD23q6airu/NkAeJcw+fJnQIxuL13asUv+dyQor3p/yL2T
    JgYwYEJ6kXpshCcmyrJjOmR9nnXL2VXH1G6EO4fzAoGBAOCQ4RlEcdMzx4+uGZ4V
    y9D/1uqF8+lhu1Vcmp/tcCngupkGYxovjezHgJfMLquag9FVqoxr4mwEtQ/ufdsh
    1HP4deRnYNOpbXJ0wHQBGAC70FAvtSHbk24Gepu6NMmDEAyCK69TYPrQ/wLrIJnw
    gjkcwc3xt4isHo1JXp0EhnaRAoGBALNdcvfkJhkF1MN50rj6/ZrASgRjiHxN+1Mv
    fvgwEF7M1x1i/0AAUtt2MiULQmnmGhWFtdVVdCBHR74h3iJCH1HIfVezB1gh0Bhd
    hAxrLeWY7TKFOdRzWggzbDgFGo3/6bxyrnx9939U0v1UZIr6lgvgIGF48E0tkjTU
    xP7ZzHn9AoGAfsEMpDnue1Kls8MkPMPG860dx8O2iI66SrNSHMiD1ooHTP++lgXL
    psgGldHEIST76izMhsAN4rLJuruIuX0Ff0sjfJbcQF0HKpVZtDImPXGVYrlR5wxv
    QzNfg5F8z6sgp0bPYE5ay/wkva+L7nndfNtBJzRxZV3f3KXk2IVU5LE=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['RELEASE_KEY1'] %>"
      iv:                "v0x2nVjnHOcrE+WD7izang=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA4eZFJ+L6sl/v/WW2VI1LKh8X3jvcBwyfz+ATaABBY/zcdEI2
    g7CSmzMmfIsP8aeoF1YuF3wxvZRQmdR2JW08pBsbgb6K7ZymM3jtho4DHYPF0NGr
    NMuH4BmKmoDCVG3eUK30QI74ysjp3WlKazfpOGels6wg++us2dH4YqYWEPKVZHad
    9eC05Zscv4hPqDBaBSNNr3Yj6FfwJgfdRkJ1TlYz8pdoHp6M2otpnpn6LwXJPhZb
    2gIdKA+q8YY9Rdbn/ffrbUx/0SXIKbOqdTA5m+Xs3FZrmSK8HvaHsqugnB7VdW0j
    wCxUKtyX/Mqzdr3GW1/r+sRm1rtXOs+dPlTuhQIDAQABAoIBAQCxu4XPsxMBwt/E
    ZAFHlv97fYk+7aPY3ALk/+zk18abD7i3s9zGUeeXOnBebt81h26GJeUPz0QnX4jm
    7zWhjse2aimDNFKETsqpFszzH8qtrx61hDGK0VPvaskVdJbw7JyMp8DUBmkSy27N
    KGlH4G6bVVkW+yfcbXnKyxv9KaWU4H1eAiforZpAegys9OZ6fA+cl5BUjp5EuN7c
    +q4PsBNXdXz9+hW/dnt6mGyzvJprJaoprifu0/P4GlAiY0xscs+n8Ho3F60uSnPb
    jGw+oaK9Fsc/97+n/MWWMMeY0Nt0kT9oIWPOJLAdOTPEnVaOq3KLZWvcoKV45NlH
    YbjT2CIlAoGBAPOd25AKrOpHPn40+SdKLv1gOMXF7MCBWYJnNKR+V0vH4ho3omhl
    y9vPcu96SJKOBl8nRcM2QEji6/uWyHcdGR9GHuvZfilsqlnzWJtXyDZZB8j0UyeA
    7HZWBt5C4DyVWFGfVNFH0c02Dy2474yzuNHFn/ZtIYJpFb2HSHDHXjzHAoGBAO1h
    3MEFEP5YsbhePE7SmJRNJH7OY6+8A+/MkeZUI4cGTtKSjZfqSog/R/bFvzhvS3BZ
    F+SIHRuoniFzt5GpoFtvKEfNbZJ4wp12WwU1tu0oxm/GURD352dllCqnELuVZVG4
    QKqbiqtog/N0DcbRJi8Kkl8BYM9wfXgUGS1woPZTAoGBANnogKXGNsdUNLz1K0wO
    mht//yhAkzXaPbNcF4VvkSwyvbcPvpC9RWz3kWpOKi4VJfPlEAy+MSBBAi5HwEZz
    W65SrYPvRl9NWM8e0UoaafbbChChIuQ5+MkcyAX1MdhfCeHwsBCGuk5hpZATVQq5
    E39n0168XPXmg1DFenGOk2evAoGANTG+5EocWsLJYIVNgmRS6Li4uunJEPJS94Oi
    Fjk4lONm+mz46dgIx6tWlwgNJ7pY714nqoCN9Uq91MU3l56pXpP0NNLmAPKqudpx
    3yMAUPjYLugD9od3BYaPw1cYutBpmfxuEU01r9+F4iJZi/oGUnhOAJgwd4u/sg7e
    7X3VtB0CgYEArOlDzR4CAXAKxAlg2Fp2dovQTZ2oty1ofJ/Wiu/35DTqyNnXvgOD
    rb0YC944eK1W2z/n4eO7rMpbTxAcOUfJ0UDDSMz7u8eFKmKSmBLIJyQctyEBZ+Z1
    LjmkFN7qjgiFwXd37wvQfOVUfgtjekGh+nXrCDmrbQSVKDWJbcoOzh8=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key:     "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:                "SFLIFnpPMWOqQaNYV3gsqg=="
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
